name = "BOMCP"
uuid = "34eb85ad-9eb0-481c-b5b9-6fa2bf859cd5"
authors = ["jmern3250 <jmern91@stanford.edu>"]
version = "1.0.0"

[deps]
BayesianOptimization = "4c6ed407-134f-591c-93fa-e0f7c164a0ec"
BeliefUpdaters = "8bb6e9a1-7d73-552c-a44a-e5dc5634aac4"
CPUTime = "a9c8d775-2e2e-55fc-8582-045d282d599e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
Kalman = "d59c0ba6-2ef2-5409-8dc5-1fd9a2b46832"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
